# This is the default config file for GibMan. Refer to README.md
# for further information on how to configure your instance of GibMan.

engine:
# Here you can list engines with the following format:
# - name: <name>
#   path: <path to engine>
# The name is used in the preset section of the configuration file.
# The engine listed at the top is used as the default.
  - name: gzdoom
    path: /path/to/DOOM/GZDoom

iwad:
# Here you can list IWADs with the following format:
# - name: <name>
#   path: <path to IWAD>
# The name is used in the preset section of the configuration file.
# The IWAD listed at the top is used as the default.
  - name: doom2
    path: /path/to/DOOM/DOOM2.WAD

search:
# Here you can list paths where gibman will look for WADs. WADs defined in a
# preset will be searched in these paths. The search is case-insensitive.
# It is expected the files have either .wad, .pk3, or .zip file extensions.
  - /path/to/DOOM

preset:
# Hypothetical example preset outlined below, which you can invoke by
# running 'gibman -p example'
  - name: example
    description: A description to help you remember what the preset is for
    engine: gzdoom
    iwad: doom2
    wad:
  # Load order is top to bottom. Do not include file extensions.
      - eviternity
      - brutality
  # Load additional arguments (args).
  # For example, to make the Woof! engine run with the '-dogs 2' option, you
  # do the following:
    args:
      - -dogs
      - 2
